name: Git Workshop Demo CI

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "chare/**"
      - "doc/**"
  
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello GitHub Actions!"
